title: Elyazid's Portfolio
email: elyazid.assouli@gmail.com
description: Personal portfolio and blog of Essoly Elyazid.
baseurl: ""
url: "https://elyazid.is-a.dev"
theme: minima
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME